services:
  sql_service:
    image: postgres:16
    container_name: sql_container
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  pipelines:
    image: etl_image:latest
    container_name: pipelines_container
    build:
      context: ./
      dockerfile: pipelines/image/dockerfile
